---
title: "Data visualization with factoextra"
output: rmarkdown::html_vignette
description: >
  Extract and Visualize the results of multivariate data analyses.
vignette: >
  %\VignetteIndexEntry{Data visualization with factoextra}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r echo=FALSE, message = FALSE, warning=FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
```


`FactoMineR2` is an R package that provides an efficient and user-friendly way to perform multivariate data analyses. `factoextra` was initially designed for `FactoMineR` but you can easily use it with `FactoMineR2` for data visualization. This vignette provides a quick overview of how to use `factoextra` with `FactoMineR2`.


```{r message = FALSE, warning=FALSE}
library(dplyr)
library(factoextra)
library(FactoMineR)
library(FactoMineR2)
library(magrittr)
data(decathlon)
```


## Eigs

```{r}
X_sup <- decathlon[, 11:13]
X_active <- decathlon[, -c(11:13)]

eigs <- X_active |>
  standardize(type = "norm") |>
  get_eigen()

df_eigs <- eigs |>
  extract(1) |>
  as.data.frame() |>
  rename(eigenvalue = values) |>
  mutate(
    `percentage of variance` = eigenvalue / sum(eigenvalue) * 100,
    `cumulative percentage of variance` = cumsum(`percentage of variance`)
  )

res_pca2 <- list(
  eig = df_eigs
)

class(res_pca2) <- "PCA"

factoextra::fviz_eig(res_pca2)
```

